# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '3.8'

services:
  mysql:
    image: docker.io/bitnami/mysql:8.0
    volumes:
      - 'mysql_data:/bitnami/mysql'
    networks:
        - sf-nw
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=bn_ghost
      - MYSQL_DATABASE=bitnami_ghost
  ghost:
    image: docker.io/bitnami/ghost:5
    restart: unless-stopped
    ports:
      - '2368:2368'
    volumes:
      - './data:/bitnami/ghost'
    depends_on:
      - mysql
    networks:
        - sf-nw
        - db
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - GHOST_DATABASE_HOST=mysql
      - GHOST_DATABASE_PORT_NUMBER=3306
      - GHOST_DATABASE_USER=bn_ghost
      - GHOST_DATABASE_NAME=bitnami_ghost

networks:
  sf-nw:
    driver: bridge
  db:

volumes:
  mysql_data:
    driver: local
