version: '3.8'

services:
  mysql:
    image: docker.io/bitnami/mysql:8.0
    restart: unless-stopped
    volumes:
      - /opt/databases/sykofizz-website/mysql:/bitnami/mysql
    networks:
      - sf-nw
      - db
    environment:
      - MYSQL_USER=ghost_user
      - MYSQL_DATABASE=ghost_db
      - MYSQL_PASSWORD=${GHOST_DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${GHOST_DATABASE_PASSWORD}-root

  ghost:
    image: docker.io/bitnami/ghost:5
    restart: unless-stopped
    ports:
      - '2368:2368'
    volumes:
      - /opt/persistence/sykofizz-website/ghost:/bitnami/ghost
    depends_on:
      - mysql
    networks:
      - sf-nw
    environment:
      - GHOST_DATABASE_HOST=mysql
      - GHOST_DATABASE_PORT_NUMBER=3306
      - GHOST_DATABASE_USER=ghost_user
      - GHOST_DATABASE_NAME=ghost_db
      - GHOST_DATABASE_PASSWORD=${GHOST_DATABASE_PASSWORD}

networks:
  sf-nw:
    driver: bridge
  db:
