version: '3.8'

services:
  mysql:
    image: docker.io/bitnami/mysql:8.0
    restart: unless-stopped
    volumes:
      - /opt/databases/sykofizz-website/mysql:/bitnami/mysql
    networks:
      - sf-nw
      - db
    environment:
      - MYSQL_USER=ghost_user
      - MYSQL_DATABASE=ghost_db
      - MYSQL_PASSWORD=${GHOST_DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${GHOST_DATABASE_PASSWORD}-root

  ghost:
    image: ghost:5
    restart: unless-stopped
    ports:
      - '2368:2368'
    volumes:
      - /opt/persistence/sykofizz-website/ghost:/var/lib/ghost/content
    depends_on:
      - mysql
    networks:
      - sf-nw
    environment:
      - NODE_ENV=production
      - database__client=mysql
      - database__connection__user=ghost_user
      - database__connection__database=ghost_db
      - database__connection__password=${GHOST_DATABASE_PASSWORD}

networks:
  sf-nw:
    driver: bridge
  db:
