version: '3.8'
services:
  mongo:
    image: mongo:jammy
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
# DATABASE_URL = "mongodb://root:password@localhost:27017/sykofizz?retryWrites=true&w=majority&authSource=admin"
