version: '3.8'

services:
  backend:
    image: haniel56/sykofizz-backend:${TAG:-latest}
    command: "granian --interface asginl sykofizz.asgi:application \
              --host 0.0.0.0 --port 8000 --workers 3 \
              --log-level ${LOG_LEVEL:-info}"
    depends_on:
      - syko_redis
    environment:
      - REDIS_URL=redis://syko_redis:6379/1
      - RUN_MIGRATION=true
      - COLLECT_STATIC=true
    networks:
      - sfizz-nw
    ports:
      - "52222:8000"
    restart: unless-stopped
    env_file:
      - .env
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  remark42:
    image: umputun/remark42:v1.14.0
    restart: unless-stopped
    volumes:
      - /mnt/glusterfs/sykofizz/remark42/srv/var:/srv/var
    ports:
      - "52223:8080"
    networks:
      - sfizz-nw
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    env_file:
      - .env

  postgres:
    image: postgres:15-alpine 
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/db
      POSTGRES_DB: sykofizz-db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
        failure_action: rollback
        monitor: 30s
      rollback_config:
        parallelism: 1
        delay: 10s 
        order: stop-first
    networks:
      - sfizz-nw 
    volumes: 
      - /mnt/glusterfs/sykofizz/postgres/db:/var/lib/postgresql/db

  syko_redis:
    networks:
      - sfizz-nw
    image: redis:7-alpine
    restart: unless-stopped
    env_file:
      - .env
    deploy:
      replicas: 1
      restart_policy:
        condition: any

networks:
  sfizz-nw:
    driver: overlay
