version: '3.8'

services: 
  backend: 
    image: haniel56/sykofizz-backend:94256d1
    command: "granian --interface asginl sykofizz.asgi:application \
              --host 0.0.0.0 --port 8000 --workers 3 \
              --log-level ${LOG_LEVEL:-info}"
    depends_on: 
      - syko_redis
    environment: 
      - REDIS_URL=redis://syko_redis:6379/1
      - RUN_MIGRATION=true
    networks:
      - sfizz-nw
    ports: 
      - "52222:8000"
    restart: unless-stopped
    env_file:
      - .env
    deploy:
      replicas: 2  # Run two replicas
      restart_policy:
        condition: any
  
  remark42:
    image: umputun/remark42:v1.13.1
    restart: unless-stopped
    volumes:
      - /mnt/glusterfs/sykofizz/remark42/srv/var:/srv/var
    ports:
      - "52223:8080"
    networks:
      - sfizz-nw
    deploy:
      replicas: 2  # Run two replicas
      restart_policy:
        condition: any
    env_file:
      - .env
  
  syko_redis:
    networks:
      - sfizz-nw
    image: redis:7-alpine
    restart: unless-stopped
    env_file:
      - .env
    deploy:
      replicas: 2  # Run two replicas for Redis
      restart_policy:
        condition: any

networks:
  sfizz-nw:
    driver: overlay
