name: Docker CI/CD -- Build and Push Docker Image (prod)

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Extract commit hash as tag
        run: |
          VERSION=$(git rev-parse --short HEAD)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            haniel56/sykofizz-backend:${{ env.VERSION }}
            haniel56/sykofizz-backend:latest
          platforms: linux/amd64,linux/arm64
